app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "posts#index"
  get "pages/about"
  get "pages/contact"

  resources :posts, :path => 'coins' do 
     resources :comments, only: [:create, :destroy, :new]

    collection do
      get :hot
      get :top
      get :newposts
      get :sideposts
    end
    
  end



  resources :users, :only =>[:show] do
    resources :relationships, only: [:create]

    collection do
      get :top
    end

  end



    resources :relationships, only: [:destroy]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',   to: 'users#show',   via: 'get'

   get "post/like/:post_id" => "likes#save_like", as: :like_post

   get "comment/heart/:comment_id" => "hearts#save_heart", as: :heart_comment


   get :search, controller: :posts




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade show alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/app/views/layouts/_navbar.html - Copy.erb
<nav class="navbar fixed-top navbar-dark bg-light">
    <div class="nav-content">

      <% if user_signed_in? %>

          <div class="nav-user">

            <div class="navbar-user-image">
              <% if current_user.avatar.attached? %>
                            <%= image_tag current_user.avatar, size: "30", class: "rounded-circle", style: "object-fit:cover" %>
                          <% else %>
                            <%= image_tag 'user.jpg', size: "25", class: "rounded-circle" %>
                          <% end %>
                        </div>

            <div class="navbar-username">
              <%= link_to current_user, style: "color:#ececec;" do %>
                <b><%= current_user.username %></b>
              <% end %>
            </div>

                    </div>




            <div class="search">
              <%= form_with url: search_path, local: true, method: :get, html: { class: "form-inline" } do |form| %>
                  <%= form.text_field :q, placeholder: "Otsing...", data: { behavior: "autocomplete" }, class: "form-control", style: "height:35px;" %>
              <% end %>
            </div>

      <% else %>


              <%= link_to "Log in", new_user_session_path, class: "navbar-button navbar-in", style: "text-decoration:none;" %>
              <%= link_to "Sign up", new_user_registration_path, class: "navbar-button navbar-new", style: "text-decoration:none;" %>


      <% end %>

          <a class="mr-auto" href="/" style="color: #333;text-decoration: none;">
            <h4 style="font-weight: 700;">UniRcoket</h4>
          </a>


        <% if user_signed_in? %>
          <%= link_to sideposts_posts_path, remote: true, id: "side-posts" do %>
            <div class="toggle sidebar js-menu-toggle" style="margin-right:20px;">
              <div class="burger-icon">
                <%= image_tag 'burger.svg', size: "20" %>
              </div>
              </div>
          <% end %>
          <% end %>
    </div>

  </nav>

app/app/views/layouts/_navbar.html.erb
<nav class="navbar nav-center fixed-top navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="/">defiboost</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	  	<div class="burger-icon">
	  		<%= image_tag 'burger.svg', size: "16" %>
	  	</div>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    <div class="navbar-nav ml-auto">
	      <%= link_to "Cryptocurrencies", root_path, class: "nav-item nav-link" %>
	      <%= link_to "About Us", pages_about_path, class: "nav-item nav-link" %>
	      <%= link_to "Contact", pages_contact_path, class: "nav-item nav-link" %>
	      	<% if !user_signed_in? %>
		      <div class="login" style="min-width:130px;">
		      	<%= link_to "Log in", new_user_session_path, class: "btn", style: "color:white;border-radius: 25px;font-size:14px;background-color: #6c63ff;letter-spacing: 1px;margin:auto;width:100%;font-weight:700;" %>
		      </div>
		    <% else %>
		      <div class="logout" style="min-width:130px;">
		      	<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn", style: "color:white;border-radius: 25px;font-size:14px;background-color: #6c63ff;letter-spacing: 1px;margin:auto;width:100%;font-weight:700;" %>
		      </div>
		    <% end %>


	    </div>
	  </div>
</nav>

app/app/views/layouts/_sidenav.html.erb
<% if user_signed_in? %>

  <aside class="sidebar">

      <div class="side-inner">

        <div class="side-profile" style="padding: 15px;">

          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, size: "75", class: "rounded-circle", style: "object-fit:cover" %>
          <% else %>
            <%= image_tag 'user.jpg', size: "75", class: "rounded-circle", style: "object-fit:cover" %>
          <% end %>

          <h5 class="name" style="margin-top:15px;">
            <%= link_to current_user, style: "color:#ececec;text-decoration:none;" do %>
              <b><%= current_user.username %></b>
            <% end %>
          </h5>

          <% if current_user.bio? %>
            <span class="bio" style="color:#5a5a5a;font-size: 16px;">"<%= current_user.bio %>"</span>
          <% end %>
        </div>


        <div class="side-menu" style="margin-top:5px;">

            <%= link_to current_user, style: "text-decoration:none;color:#ececec;" do %>
              <div class="side-menu-item">
                <div class="side-menu-item-color"></div>
                <div class="side-menu-inner-item">               
                    <i class="fas fa-user mr-4" style="width:20px;text-align:center;"></i>
                    Minu profiil
                </div>
              </div>
            <% end %>
            <%= link_to top_users_path, style: "text-decoration:none;color:#ececec;" do %>
              <div class="side-menu-item">
                <div class="side-menu-item-color"></div>
                <div class="side-menu-inner-item">  
                    <i class="fas fa-star mr-4" style="width:20px;text-align:center;"></i>
                    TOP mängurid
                </div>
              </div>
            <% end %>

            <%= link_to edit_user_registration_path, style: "text-decoration:none;color:#ececec;" do %>
              <div class="side-menu-item">
                <div class="side-menu-item-color"></div>
                <div class="side-menu-inner-item">
                    <i class="fas fa-cog mr-4" style="width:20px;text-align:center;"></i>
                    Seaded
                </div>
              </div>
            <% end %>

            <%= link_to destroy_user_session_path, method: :delete, style: "text-decoration:none;color:#ececec;" do %>
              <div class="side-menu-item">
                <div class="side-menu-item-color"></div>
                <div class="side-menu-inner-item">
                    <i class="fas fa-sign-out-alt mr-4" style="width:20px;text-align:center;"></i>
                    Logi välja
                </div>
              </div>
            <% end %>

        </div>
        <div class="side-menu-post-hot" style="padding-left:15px;padding-top:10px;border-top:1px solid #333333;margin-bottom:10px;">
          <h6 style="margin-bottom:0px;">Täna kuum</h6>
        </div>

        <div id="side-top-post">

        </div>



      </div> 
  </aside>

<% end %>

app/app/views/layouts/_widget.html.erb
            <div class="search" style=";margin-left:20px;margin-bottom:20px;">
              <%= form_with url: search_path, local: true, method: :get, html: { class: "form-inline" } do |form| %>
                  <%= form.text_field :q, placeholder: "Search...", data: { behavior: "autocomplete" }, class: "form-control", style: "height:47px;width:350px;" %>
              <% end %>
            </div>



      <div class="widget" style="width:350px;border: 1px solid #ebeef0;margin-left:20px;border-radius:15px;margin-bottom:20px;">
        <div class="widget-up" style="padding:15px 15px 15px 20px;border-radius:15px 15px 0 0;border-bottom: 1px solid #ebeef0;display:flex;">
          <h5 style="font-weight:700;margin-bottom:0;">About</h5>

              <a class="ml-auto" href="https://discord.gg/dak9xbwD" target="_blank"><i class="fab fa-discord" style="font-size:24px;color:#6c63ff;"></i></a>

        </div>
        <div class="widget-body" style="padding:20px;">
          <% if user_signed_in? %>
            <div class="widget-welcome" style="margin-bottom:20px;">
              <% if current_user.admin %>
                <b><p style="color:#e0245e;">CEO</p></b>
              <% end %>


                          <% if current_user.avatar.attached? %>
                            <%= image_tag current_user.avatar, size: "35", class: "rounded-circle", style: "object-fit:cover" %>
                          <% else %>
                            <%= image_tag 'user.jpg', size: "35", class: "rounded-circle" %>
                          <% end %>

                <%= link_to current_user, style: "font-weight:700; color: #333;" do %>
                  <% current_user.username %>
                <% end %>
                
            </div>
          <% end %>
          <div class="widget-info" style="margin-bottom:20px;">
            <b>Defiboost</b> is a community driven DeFi token paradise. Here you can find different shit and memecoins. Good luck searching.
          </div>

          <div class="widget-members">
              Members: <b><%= User.count %></b>
          </div>

          <div class="widget-online">
              Online: <b><%= User.online.count %></b>
          </div>

          <% if !user_signed_in? %>
            <div class="widget-signup" style="padding-top:30px;">
              <%= link_to "Sign up", new_user_registration_path, class: "btn", style: "color:white;border-radius: 25px;font-size:14px;background-color: #6c63ff;letter-spacing: 1px;margin:auto;width:100%;font-weight:700;" %>
            </div>
          <% end %>

        </div>
      </div>

<div class="widget-sticky" style="position: sticky;top: 90px;position: -webkit-sticky;">

      <div class="widget" style="width:350px;border: 1px solid #ebeef0;margin-left:20px;border-radius:15px;margin-bottom:20px;">
        <div class="widget-up" style="padding:15px 15px 15px 20px;border-radius:15px 15px 0 0;border-bottom: 1px solid #ebeef0;">
          <h5 style="font-weight:700;margin-bottom:0;">Promoted</h5>
        </div>
        <div class="widget-body" style="padding:20px;margin-bottom:-20px;">
          <%= render 'posts/promoted_post'%>
        </div>
      </div>

      <div class="widget" style="width:350px;border: 1px solid #ebeef0;margin-left:20px;border-radius:15px;margin-bottom:20px;">
        <div class="widget-up" style="padding:15px 15px 15px 20px;border-radius:15px 15px 0 0;border-bottom: 1px solid #ebeef0;">
          <h5 style="font-weight:700;margin-bottom:0;">#1 Hot today</h5>
        </div>
        <div class="widget-body" style="padding:20px;">
          <%= render 'posts/widget_top'%>
        </div>
      </div>

</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeFi Lab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>

    <div class="container">


        <%= render 'layouts/navbar' %>

      <div id="main" style="display:flex;">
        <div class="main2" style="width:100%;">
          <%= render 'layouts/alerts'%>
          <%= yield %>
        </div>


        <div class="main3" id="widget">
          <%= render 'layouts/widget'%>
        </div>


      </div>
    </div>


  </body>

</html>