app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "posts#index"
  get "pages/about"
  get "pages/contact"

  resources :posts, :path => 'coins' do 
     resources :comments, only: [:create, :destroy, :new]

    collection do
      get :hot
      get :top
      get :newposts
      get :sideposts
    end
    
  end



  resources :users, :only =>[:show] do
    resources :relationships, only: [:create]

    collection do
      get :top
    end

  end



    resources :relationships, only: [:destroy]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',   to: 'users#show',   via: 'get'

   get "post/like/:post_id" => "likes#save_like", as: :like_post

   get "comment/heart/:comment_id" => "hearts#save_heart", as: :heart_comment


   get :search, controller: :posts




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }, :length => { :maximum => 25 }
  validates :bio, :length => { :maximum => 100 }

  has_many :likes, dependent: :destroy
  has_many :received_likes, through: :posts, class_name: "Like"
  has_many :hearts, dependent: :destroy

  has_many :following, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  
  has_many :posts, dependent: :destroy do

    def today
      where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))
    end

  end

    def received_likes
      posts.map { |p| p.likes.size}.reduce(0, :+)
    end

  has_many :comments, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy

  scope :online , ->{where("last_seen_at > ?", 5.minutes.ago) }


end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  
  def show
  	@user = User.find(params[:id])

  	@posts = @user.posts.order('created_at desc').paginate(page: params[:page], per_page: 1)
    @posts = @posts.includes(:comments, :likes)
    @posts = @posts.includes(image_attachment: :blob)

  	@rel = @user.followers.find_by(follower: current_user)
  end

  def followers
  end

  def top
    @users = User.includes(:posts, avatar_attachment: :blob ).limit(10).sort_by { |p| p.received_likes}.reverse!
  end


end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/users/_follow.html.erb
<%= link_to 'Follow', user_relationships_path(@user), method: :post, remote: :true, class: "btn btn-load-more" unless @rel.present? %>

app/app/views/users/_follow_form.erb
<div id="follow_form">
	<%= render 'follow'%>
	<%= render 'unfollow' if @rel.present? %>
</div>

app/app/views/users/_unfollow.html.erb
	<%= link_to 'Unfollow', relationship_path(@rel.id), method: :delete,  remote: :true, class: "btn btn-load-more"%>

app/app/views/users/index.html.erb
USERS/INDEX

app/app/views/users/show.html.erb
<div class="user-page-content" style="margin-top:10px;border-radius:15px;">
	<div class="user-page-img">
		<% if @user.avatar.attached? %>
			<%= image_tag @user.avatar, size: "120", class: "rounded-circle", style: "object-fit:cover"  %>
		<% else %>
			<%= image_tag 'user.jpg', size: "120", class: "rounded-circle", style: "object-fit:cover"  %>
		<% end %>
	</div>

	<br>

	<div class="user-page-name">
		<h5><b><%= @user.username %></b></h5>
	</div>


	<% if @user.bio? %>
		<div class="user-page-bio" style="padding:0 20px 20px 20px;text-align: center;">
			<%= @user.bio %>
		</div>
	<% end %>

	<% if user_signed_in? %>
		<div class="user-page-button" style="text-align:center;">
			<% if @user == current_user %>
				<%= link_to "Edit", edit_user_registration_path, class: "btn", style: "color:white;background-color:#007bff;width:130px;border-radius:25px;" %>
			<% else %>
				<%= render 'follow_form' %>
			<% end %>
		</div>
	<% end %>


	<div class="user-created-at" style="display:flex;justify-content: center;margin: 20px 0 10px 0;">
		<b>Joined <%= time_ago_in_words(@user.created_at).gsub('about','') + ' ago' %></b>
	</div>

		<div class="user-page-actions" style="margin-top:30px;margin-bottom:30px;">
			<div class="user-page-actions-item">
				<div class="user-page-actions-item-number" id="followers">
					<%= @user.followers.count %>
				</div>
				<div class="user-page-actions-text">
					<%= "Follower".pluralize (@user.followers.count) %>
				</div>
			</div>

			<div class="user-page-actions-item" style="text-align:center;">
				<div class="user-page-actions-item-number">
					<%= @user.received_likes %>
				</div>
				<div class="user-page-actions-text">
					<%= "Like".pluralize (@user.received_likes) %>
				</div>
			</div>

			<div class="user-page-actions-item" style="text-align:center;">
				<div class="user-page-actions-item-number">
					<%= @user.posts.size %>
				</div>
				<div class="user-page-actions-text">
					<%= "Post".pluralize (@user.posts.size) %>
				</div>
			</div>
		</div>


	<div id="user-page-posts">


    		<%= render @posts %>


	</div>



			<div class="load-more-user-posts-button" style="padding-bottom:50px;margin-top:10px;">
		      <% if @posts.next_page %>
		          <%= link_to user_path(:page => @posts.next_page),data: { disable_with: "Loading..." }, class: "btn btn-load-more", id: "load-more-user-posts", remote: true do %>
		            Load more

		          <% end %>

		      <% end %>
		    </div>

			<div id="postituste-lopp">
			  <button class="btn btn-lopp">You have reached bottom! - Back to top</button>
			</div>

 

</div>

app/app/views/users/show.js.erb
$('#user-page-posts').append('<%= j render @posts %>');
$('#load-more-user-posts').attr('href', '<%= user_path page: @posts.next_page %>');


<% if !@posts.next_page %>
	$('.load-more-user-posts-button').remove();
	$('#postituste-lopp').show();
<% end %>

app/app/views/users/top.html.erb
<div class="users-top-page" style="height: 100vh;">
  	<div class="top" style="display:block;text-align:center;">
  		<h4 style="font-weight: 800;">TOP</h4>
  	</div>
  		<div class="rida-up" style="display:flex;align-items: center;background-color: #2b2b2b;padding: 15px;border-radius:10px;margin-bottom:15px;margin-top:20px;">

  			<div class="rida-number" style="width:35px;text-align: center;margin-right:20px;font-size: 18px;">
	    		<b>#</b>
	    	</div>

	    	<div class="rida-kasutaja" style="margin-right:10px;">
				<b>Mängur</b>
	      	</div>

	      	<div class="rida-posts ml-auto" style="width:35px;text-align: center;">
	      		<%= embedded_svg 'heart.svg', class: "users-heart-img" %>
	      	</div>
	    </div>



  	<% @users.each.with_index(1) do |user, index| %>
  		<div class="rida-terve <%= 'top1' if index == 1 %>" style="display:flex;align-items: center;background-color: #2b2b2b;padding: 15px;border-radius:10px;margin-bottom:15px;">

  			<div class="rida-number" style="width:35px;text-align: center;margin-right:20px;">
	    		<b><%= index %></b>
	    	</div>

	    	<div class="rida-pilt" style="margin-right:10px;">
			    <% if user.avatar.attached? %>
		          <%= image_tag user.avatar, size: "30", class: "rounded-circle", style: "object-fit:cover" %>
		        <% else %>
		          <%= image_tag 'user.jpg', size: "30", class: "rounded-circle", style: "object-fit:cover" %>
		        <% end %>
		    </div>

	    	<div class="rida-nimi">
	      		<b><%= link_to user.username, (user), style: "color:#ececec;" %></b>
	      	</div>

	      	<div class="rida-posts ml-auto" style="min-width:35px;text-align: center;">
	      		<b><%= user.received_likes %></b>
	      	</div>
	    </div>

	<% end %>
</div>