app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "posts#index"
  get "pages/about"
  get "pages/contact"

  resources :posts, :path => 'coins' do 
     resources :comments, only: [:create, :destroy, :new]

    collection do
      get :hot
      get :top
      get :newposts
      get :sideposts
    end
    
  end



  resources :users, :only =>[:show] do
    resources :relationships, only: [:create]

    collection do
      get :top
    end

  end



    resources :relationships, only: [:destroy]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',   to: 'users#show',   via: 'get'

   get "post/like/:post_id" => "likes#save_like", as: :like_post

   get "comment/heart/:comment_id" => "hearts#save_heart", as: :heart_comment


   get :search, controller: :posts




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :image, dependent: :destroy
  has_one_attached :cover, dependent: :destroy

  validate :user_post_limit, :on => :create
  validates :body, presence: true
  validates :title, presence: true,
					length: {minimum: 5}

#kuumade postituste scope
  scope :hot, -> { joins("LEFT OUTER JOIN Likes ON likes.post_id = posts.id 
                     AND likes.created_at BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}'")
                    .group("posts.id").order("COUNT(likes.id) DESC") }
#top postituste scope
  scope :top, ->{ where("likes_count >= ?", 0,).order("likes_count DESC") }
#uute postituste scope
  scope :newposts, ->{ order('created_at DESC') }

#muudab postituse show page URL-i, lisab ID-le juurde pealkirja.
  def to_param
    "#{id} #{title}".parameterize
  end


	private 

# Kontrollib kas kasutaja onteinud päevas rohkem kui 3 postitust.
	  def user_post_limit 
	   if user.posts.today.count >= 15
	     errors.add(:base, "Päevalimiit on täis")
	   else

	   end
	  end


end

app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show, :hot, :top, :newposts, :search]
  before_action :post_omanik, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.top.includes(user: :avatar_attachment).paginate(page: params[:page], per_page: 5)
    @posts = @posts.includes(:comments, :likes)
    @posts = @posts.includes(image_attachment: :blob)


  end

  def hot
    @posts = Post.hot.includes(user: :avatar_attachment).paginate(page: params[:page], per_page: 5)
    @posts = @posts.hot.includes(:comments, :likes)
    @posts = @posts.hot.includes(image_attachment: :blob)
    render action: :index

  end

  def top
    @posts = Post.top.includes(user: :avatar_attachment).paginate(page: params[:page], per_page: 5)
    @posts = @posts.top.includes(:comments, :likes)
    @posts = @posts.top.includes(image_attachment: :blob)
    render action: :index
  end

  def newposts
    @posts = Post.newposts.includes(user: :avatar_attachment).paginate(page: params[:page], per_page: 5)
    @posts = @posts.newposts.includes(:comments, :likes)
    @posts = @posts.newposts.includes(image_attachment: :blob)
    render action: :index
  end

  def widget_top

  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = if params[:comment]
                  @post.comments.where(id: params[:comment])
                else
                  @post.comments.where(parent_id: nil)
                end

    @comments = @comments.order('created_at asc').paginate(page: params[:page], per_page: 2)

  end


  def search

    @posts = Post.ransack(title_cont: params[:q]).result(distinct: true)
    
    respond_to do |format|
      format.html {}
      format.json {
        @posts = @posts.limit(7)
      }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def hide_new_form

  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    if current_user.admin
      @post = Post.new(post_params)
      @post.user = current_user

      respond_to do |format|
          if @post.save
            format.html { redirect_to @post, notice: "Postitus edukalt loodud!" }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
      end

    else
        flash[:notice] = 'You dont have permission to do that!'
        redirect_to posts_path
    end

  end

  def post_omanik
    @post = Post.find(params[:id])
      unless @post.user_id == current_user.id || current_user.admin
        flash[:notice] = 'Viga! Antud postitus ei ole Teie loodud!'
      redirect_to posts_path
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Postitus edukalt uuendatud!" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Postitus edukalt kustutatud!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :cover, :website, :pancake, :poocoin, :bscscan, :telegram)
    end
end

app/app/helpers/posts_helper.rb
module PostsHelper

end

app/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>


  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, 'Pealkiri' %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :body, 'Sisu' %>
    <%= form.text_area :body, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :website, 'Website' %>
    <%= form.text_area :website, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :pancake, 'Pancake' %>
    <%= form.text_area :pancake, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :poocoin, 'Poocoin' %>
    <%= form.text_area :poocoin, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :bscscan, 'Bscscan' %>
    <%= form.text_area :bscscan, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :telegram, 'Telegram' %>
    <%= form.text_area :telegram, class: "form-control"  %>
  </div>

  <%= form.label :image, 'Logo' %><br>
  <%= form.file_field :image %>

  <br>

  <%= form.label :cover, 'Cover' %><br>
  <%= form.file_field :cover %>

  <div class="actions" style="margin-top:10px;">
    <%= form.submit "Postita", class: "btn btn-success" %>
  </div>
<% end %>

app/app/views/posts/_post.html.erb
  <div class="card" id="post-index-page" style="margin-bottom:20px;">
        <div class="row" id="post-id" style="margin: 0;">

              <%= link_to post_path(post), :class => 'post-image' do %>
                <% if post.image.attached? %>
                  <%= image_tag post.image, class: "post-image" %>
                <% end %>
              <% end %>

            <div class="col" id="post-body" style="padding:10px;">
                <div class="card-block px-2">

                  <div class="post-up" style="display:flex;">
                    <h4 class="card-title" style="font-weight:600;letter-spacing: 0px;margin-bottom:0.3rem;"><%= link_to post.title, (post), style: "color:#333;" %></h4>
                    
                      <div class="ml-auto" style="color:#ff8200;">
                        <% if post.sticky? %>
                          <b>Promoted</b>
                        <% end %>
                      </div>
                  </div>

                    <div class="post-date">
                      Listed <%= time_ago_in_words(post.created_at).gsub('about','') + ' ago' %>
                    </div>
                    <p class="card-text" style="margin-top:5px;"><%= post.body %></p>
                </div>

                  <div class="" style="margin-top:40px;padding-left:5px;">
                    <div class="post-nupud" style="position:absolute; bottom:10px;">

                      <% if user_signed_in? %>
                        <div class="post-heart like-<%= post.id %> <%= 'active' if post.likes.find { |like| like.user_id == current_user.id} %>" data-id="<%= post.id %>">
                          <%= embedded_svg 'heart.svg', class: "heart-img" %>
                        </div>
                      <% else %>
                        <%= link_to new_user_session_path do %>
                          <div class="post-heart-unlogged">
                            <%= embedded_svg 'heart.svg', class: "heart-img" %>
                          </div>
                        <% end %>
                      <% end %>


                          <div class="post-heart-number" id="post-<%= post.id %>-likes">
                            <%= post.likes.size %>

                          </div>

                        <% if user_signed_in? %>
                          <%= link_to post_path(post) do %>
                            <div class="post-comment <%= 'active' if post.comments.find { |comment| comment.user_id == current_user.id} %>">
                              <%= embedded_svg 'comment.svg', class: "comment-img" %>
                            </div>
                          <% end %>
                        <% else %>
                          <%= link_to new_user_session_path do %>
                            <div class="post-comment">
                              <%= embedded_svg 'comment.svg', class: "comment-img" %>
                            </div>
                          <% end %>
                        <% end %>

                        <div class="post-comment-number">
                          <%= post.comments.size %>
                        </div>
                    </div>
                  </div>
            </div>
        </div>
  </div>

app/app/views/posts/_promoted_post.html.erb
          <% @promoted_post.each do |post| %>
              <%= link_to (post), style: "text-decoration:none;color:#333;" do %>
                <div class="side-menu-post" style="display:flex;margin-bottom:20px;">
                  <% if post.image.attached? %>
                    <%= image_tag post.image, class: "side-menu-post-image", style: "border-radius:50%;" %>
                  <% end %>
                  <div class="side-menu-post-text" style="display:block;padding-left:10px;">

                        <h6 style="font-weight:700;line-height: 65px;margin-bottom:0px;"><%= post.title %></h6>
                        

                  </div>

                </div>
              <% end %>
          <% end %>

app/app/views/posts/commentcreate.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");

app/app/views/posts/create.js.erb
$('#test form').remove();
$('#test a').show();
$('#posts').prepend("<%= j render @post %>");

app/app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= form_with(model: @post) do |form| %>


  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, 'Title' %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :body, 'Description' %>
    <%= form.text_area :body, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :website, 'Website' %>
    <%= form.text_area :website, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :pancake, 'Pancake' %>
    <%= form.text_area :pancake, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :poocoin, 'Poocoin' %>
    <%= form.text_area :poocoin, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :bscscan, 'Bscscan' %>
    <%= form.text_area :bscscan, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :telegram, 'Telegram' %>
    <%= form.text_area :telegram, class: "form-control"  %>
  </div>

  <%= form.label :image, 'Logo' %><br>
  <%= form.file_field :image %>

  <br>

  <%= form.label :cover, 'Cover' %><br>
  <%= form.file_field :cover %>

<br>

  <div class="actions" style="margin-top:20px;">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/app/views/posts/hide_new_form.js.erb
$('#newtest').remove();
$('#test a').show();

app/app/views/posts/index.html.erb
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <div id="add-crypto" style="display:inline-block;width:100%;margin-bottom:20px;">
              <%= link_to new_post_path, class: "btn", style: "color:white;border-radius: 25px;font-size:14px;background-color: #6c63ff;letter-spacing: 1px;margin:auto;width:100%;font-weight:700;" do %>
              Add Cryptocurrency
              <% end %>
            </div>
          <% end %>
        <% end %>

      
      <div class="" style="display:flex;">
        <div id="posts" style="width:100%;">
          <div class="posts-index-actions">
            <div class="posts-actions">
              <div class="col">
                <%= link_to top_posts_path, :class => current_page?(top_posts_path) ? "posts-active" : "" do %>
                  <div class="topposts">
                    <b>Top</b>
                  </div>
                <% end %>
              </div>

              <div class="col">
                <%= link_to hot_posts_path, :class => current_page?(hot_posts_path) ? "posts-active" : "" do %>
                  <div class="hotposts">
                    <b>Hot</b>
                  </div>
                <% end %>
              </div>

              <div class="col">
                <%= link_to newposts_posts_path, :class => current_page?(newposts_posts_path) ? "posts-active" : ""  do %>
                  <div class="newposts">
                    <b>New</b>
                  </div>
                <% end %>
              </div>

            </div>
          </div>

          <%= render @posts %>

        </div>



      </div>

<div id="index-posts-button">
    <div id="load-more-button" style="padding-bottom:30px;">
      <% if current_page?(root_path) || current_page?(posts_path) %>
        <% if @posts.next_page %>
              <%= link_to top_posts_path(:page => @posts.next_page),data: { disable_with: "Loading..." }, class: "btn btn-load-more", id: "load-more-posts", remote: true do %>
                Load More
              <% end %>
        <% end %>
      <% end %>

      <% if current_page?(hot_posts_path) %>
        <% if @posts.next_page %>
              <%= link_to hot_posts_path(:page => @posts.next_page),data: { disable_with: "Loading..." }, class: "btn btn-load-more", id: "load-more-posts", remote: true do %>
                Load More
              <% end %>
        <% end %>
      <% end %>

      <% if current_page?(newposts_posts_path) %>
        <% if @posts.next_page %>
              <%= link_to newposts_posts_path(:page => @posts.next_page),data: { disable_with: "Loading..." }, class: "btn btn-load-more", id: "load-more-posts", remote: true do %>
                Load More
              <% end %>
        <% end %>
      <% end %>

      <% if current_page?(top_posts_path) %>
        <% if @posts.next_page %>
              <%= link_to top_posts_path(:page => @posts.next_page),data: { disable_with: "Loading..." }, class: "btn btn-load-more", id: "load-more-posts", remote: true do %>
                Load More
              <% end %>
        <% end %>
      <% end %>
    </div>

    <div id="postituste-lopp">
      <button class="btn btn-lopp">You have reached bottom! - Back to top</button>
    </div>

</div>

app/app/views/posts/index.js.erb
$('#posts').append('<%= j render @posts %>');

<% if current_page?(root_path) || current_page?(posts_path) %>
	$('#load-more-posts').attr('href', '<%= top_posts_path page: @posts.next_page %>');
<% end %>

<% if current_page?(hot_posts_path) %>
	$('#load-more-posts').attr('href', '<%= hot_posts_path page: @posts.next_page %>');
<% end %>

<% if current_page?(newposts_posts_path) %>
	$('#load-more-posts').attr('href', '<%= newposts_posts_path page: @posts.next_page %>');
<% end %>

<% if current_page?(top_posts_path) %>
	$('#load-more-posts').attr('href', '<%= top_posts_path page: @posts.next_page %>');
<% end %>


<% if !@posts.next_page %>

	$('#load-more-button').remove();
	$('#postituste-lopp').show();

<% end %>

app/app/views/posts/like.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").addClass("active");
<% else %>
$(".like-<%= @post_id %>").removeClass("active");
<% end %>

$("#post-<%= @post_id %>-likes").html('<%= escape_javascript(@post_likes) %>');

app/app/views/posts/new.html.erb
<div class="new-posts-page" style="margin-top:10px;">
	<h1 style="font-weight: 700;">Add cryptocurreny</h1>

	<br>

	<%= render 'form', post: @post %>

</div>

app/app/views/posts/new.js.erb
$('#test a').hide().parent().append("<%= j render 'form', post: @post %>").hide().fadeIn(250);

app/app/views/posts/show.html.erb
<div class="card" style="border: 1px solid #ebeef0;border-radius: 0px;">

                      <div class="post-image-show">
                      <% if @post.cover.attached? %>
                         <%= image_tag @post.cover, class: "post-image", style: "width:100%;height:275px;border-radius:0px;" %>
                      <% end %>
                    </div>

  <div class="post-logo-show" style="margin-top:-75px;margin-left:10px;z-index: 20;">
    <% if @post.image.attached? %>
      <%= image_tag @post.image, style: "width:115px;height:115px;border-radius:50%;padding: 1px;background-color: #fff;" %>
    <% end %>
  </div>

  <div class="post-show-body" style="padding:15px;">
    <% if @post.sticky? %>
      <p style="color:#ff8200;margin-bottom:0px;font-weight: 700;">Promoted</p>
    <% end %> 

                    <div class="post-show-upper" style="display: flex;">
                      <h3 style="font-weight:700;letter-spacing: 0px;">
                        <%= @post.title %>
                      </h3>

                      <div class="post-right ml-auto">
                        <% if user_signed_in? %>
                          <% if @post.user == current_user || current_user.admin %>
                            <div class="dropdown ml-auto">
                              <div class="post-dots" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  <%= embedded_svg 'dots.svg',class: 'post-dots-img' %>
                              </div>
                                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">      
                                      <a><%= link_to "Edit", edit_post_path(@post), class: "dropdown-item", id: "post-muuda" %></a>
                                    
                                      <a><%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: 'Kas olete kindel?'}, class: "dropdown-item", id: "post-kustuta" %></a>
                                  </div>
                            </div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>

                        <div class="post-marketing-logos" style="display:flex;margin-bottom:10px;">
                          <a href="<%= @post.pancake %>" target="_blank"><%= embedded_svg 'pannkook.svg', class: "post-marketing" %></a>
                          <a href="<%= @post.poocoin %>" target="_blank"><%= embedded_svg 'poocoin.svg', class: "post-marketing" %></a>
                          <a href="<%= @post.bscscan %>" target="_blank"><%= embedded_svg 'bscscan.svg', class: "post-marketing" %></a>
                          <a href="<%= @post.telegram %>" target="_blank" style="text-decoration: none;"><i class="fab fa-telegram post-marketing" style="color:#28a8e9;"></i></a>
                        </div>

 

                          <a href="" target="_blank" ></a> 
                          <%= link_to @post.website, url_for(@post.website), :target => "_blank" %>   


                


                    <div class="post-body">

                        <div class="post-text">
                          <p><%= @post.body %></p>
                        </div>
            
                    </div>


                <div class="post-nupud">
                  
                  <% if user_signed_in? %>
                    <div class="post-heart like-<%= @post.id %> <%= 'active' if @post.likes.find { |like| like.user_id == current_user.id} %>" data-id="<%= @post.id %>">
                      <%= embedded_svg 'heart.svg', class: "heart-img" %>
                    </div>
                  <% else %>
                    <%= link_to new_user_session_path do %>
                      <div class="post-heart-unlogged">
                        <%= embedded_svg 'heart.svg', class: "heart-img" %>
                      </div>
                    <% end %>
                  <% end %>

                      <div class="post-heart-number" id="post-<%= @post.id %>-likes">
                        <%= @post.likes.size %>
                      </div>

                      <% if user_signed_in? %>
                        <div class="post-comment <%= 'active' if @post.comments.find { |comment| comment.user_id == current_user.id} %>">
                          <%= embedded_svg 'comment.svg', class: "comment-img" %>
                        </div>
                      <% else %>
                        <%= link_to new_user_session_path do %>
                          <div class="post-comment">
                            <%= embedded_svg 'comment.svg', class: "comment-img" %>
                          </div>
                        <% end %>
                      <% end %>
    

                      <div class="post-comment-number">
                        <%= @post.comments.size %>
                      </div>

                </div>
  </div>
</div>

<div class="post-show-comments" style="padding:15px;border: 1px solid #ebeef0;margin-top:20px;margin-bottom:20px;">
  <% if user_signed_in? %>
    <div class="comment-area">
      <%= form_with model: [@post, @comment], local: false do |f| %>
        <%= f.text_area :body, placeholder: "Add comment...", class: "form-control" %>
        <br>

        <div class="send-comment icon">
          <%= f.submit "Submit", :type => :image, :src => image_path("send-comment.svg"), class: "send-comment-img", style: "outline:none;" %>
        </div>


      <% end %>

    </div>

  <% else %>

    <div class="comment-login">
      <p>Please <%= link_to "login", new_user_session_path, style: "color:#6c63ff;" %> or <%= link_to "sign up", new_user_registration_path, style: "color:#6c63ff;" %> to comment to our comments section.</p>
    </div>

  <% end %>


      <div id="comment_pane">


        <% @comments.includes(:hearts, :replies).order("created_at ASC").each do |comment| %>


            <%= render 'comments/comment', comment: comment %>


        <% end %>

      </div>


      <% if @comments.next_page %>
        <div class="load-more-comments" style="margin-top:10px;">
          <%= link_to post_path(:page => @comments.next_page),data: { disable_with: "Laen..." }, class: "btn btn-load-more", id: "load-more-comments", remote: true do %>
            Load more comments (<%= @comments.size %>)
          <% end %>
        </div>
      <% end %>

</div>

app/app/views/posts/show.js.erb
$('#comment_pane').append('<%= j render @comments %>');
$('#load-more-comments').attr('href', '<%= post_path page: @comments.next_page %>');


<% if !@comments.next_page %>
$('#load-more-comments').remove();
<% end %>