app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "posts#index"
  get "pages/about"
  get "pages/contact"

  resources :posts, :path => 'coins' do 
     resources :comments, only: [:create, :destroy, :new]

    collection do
      get :hot
      get :top
      get :newposts
      get :sideposts
    end
    
  end



  resources :users, :only =>[:show] do
    resources :relationships, only: [:create]

    collection do
      get :top
    end

  end



    resources :relationships, only: [:destroy]

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',   to: 'users#show',   via: 'get'

   get "post/like/:post_id" => "likes#save_like", as: :like_post

   get "comment/heart/:comment_id" => "hearts#save_heart", as: :heart_comment


   get :search, controller: :posts




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true

  validates :body, presence: true, allow_blank: false

  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  has_many :hearts, dependent: :destroy


end

app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post
	before_action :authenticate_user!


  def create
  	@comment = @post.comments.new(comment_params)
  	@comment.user = current_user
    @comment.save

  end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(parent_id: params[:parent_id])
  end

  def destroy
  	@comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id || @post.user == current_user || current_user.admin
    	@comment.destroy
    else
        flash[:notice] = 'Viga! Antud kommentaar ei ole Teie loodud!'
        redirect_to post_path(@post)
    end

  end


  private
  def comment_params
  	params.require(:comment).permit(:body, :post_id, :parent_id)
  end

  def set_post
  	@post = Post.find(params[:post_id])
  end
end

app/app/helpers/comments_helper.rb
module CommentsHelper
end

app/app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %>
  <div id="comment-<%= comment.id %>">

    <div class="comment">
          <div class="comment-left" style="text-align:center;">

            <div class="comment-user-img">
              <% if comment.user.avatar.attached? %>
                <%= image_tag comment.user.avatar, size: "30", class: "rounded-circle", style: "object-fit:cover" %>
              <% else %>
                <%= image_tag 'user.jpg', size: "30", class: "rounded-circle" %>
              <% end %>

              <% if comment.user.last_seen_at > 5.minutes.ago %>
                    <div style="position:absolute;bottom:-2px;right: 0;">
                      <%= image_tag 'aktiivne.svg', size: "13" %>
                    </div>
              <% end %>
            </div>

          </div>

          <div class="comment-middle">
            <div class="comment-middle-up">

                  <div class="comment-username">
                    
                    <% if comment.user.admin %>
                      <%= link_to comment.user.username, (user_path(@user) if @user = comment.user), style: "color:#e0245e;" %>
                    <% else %>
                      <%= link_to comment.user.username, (user_path(@user) if @user = comment.user), style: "color:#333;" %>
                    <% end %>

                    <div class="comment-date">
                      <%= time_ago_in_words(comment.created_at).gsub('about','') + ' ago' %>
                    </div>

                  </div>

            </div>

            <div class="comment-body-sector" style="display:block;">

              <div class="comment-body" id="kommentaar" style="padding: <%= '10px' if comment.user == current_user %>;color: <%= 'white' if comment.user == current_user %>;background-image:<%= 'linear-gradient(139deg, rgba(250,177,219,1) 0%, rgba(255,219,126,1) 100%)' if comment.user == current_user %>">
                  <%= comment.body %>
              </div>

              <div class="comment-actions" style="display:flex;margin-top: 10px;font-size: 12px;font-weight: 500;">
                  <div class="comment-vasta">
                    <% if user_signed_in? %>
                      <%= link_to 'Reply', new_post_comment_path(@post, parent_id: comment.id), remote: true, style: "color:#333;" %>
                    <% end %>
                  </div>


                <div class="comment-kustuta" style="display:flex;">
                  <% if user_signed_in? %>
                    <% if comment.user == current_user || @post.user == current_user || current_user.admin %>
                      <div class="comment-actions-triip" style="margin-left:5px; margin-right:5px;">|</div>
                        <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: {confirm: 'Kas olete kindel?'}, remote: true, style: "color:#333;" %>
                    <% end %>
                  <% end %>
                </div>
                
              </div>

            </div>


                
          </div>


            <div class="comment-right" style="display:inline-block;text-align:center;">
              <div class="comment-right-up">

                    <% if user_signed_in? %>

                      <div class="comment-heart heart-<%= comment.id %> <%= 'active' if comment.hearts.find { |heart| heart.user_id == current_user.id} %>" data-id="<%= comment.id %>">
                        <%= embedded_svg 'heart.svg', class: "comment-heart-img" %>
                      </div>

                    <% else %>
                      <%= link_to new_user_session_path do %>
                        <div class="comment-heart">
                          <%= embedded_svg 'heart.svg', class: "comment-heart-img" %>
                        </div>
                      <% end %>
                    <% end %>



              </div>

                    <div id="comment-<%= comment.id %>-hearts" style="margin-top:10px;font-size: 11px;">
                      <%= comment.hearts.size %>
                    </div>

            </div>


    </div>

    <div id="reply-form-<%= comment.id %>"></div>

    <div id="comment_pane_reply-<%= comment.id %>">
      <% if comment.replies.any? %>
          <% comment.replies.includes(:hearts).order("created_at ASC").each do |reply| %> 
            <%= render partial: 'comments/reply', locals: { reply: reply } %>
          <% end %>
      <% end %>
    </div>

  </div>

    

<% end %>

app/app/views/comments/_reply.html.erb
<div id="comment-<%= reply.id %>">
  <div class="ml-5">
      <div class="reply">
          <div class="comment-left">
            <div class="comment-user-img">
              <% if reply.user.avatar.attached? %>
                <%= image_tag reply.user.avatar, size: "30", class: "rounded-circle", style: "object-fit:cover" %>
              <% else %>
                <%= image_tag 'user.jpg', size: "30", class: "rounded-circle" %>
              <% end %>

                <% if reply.user.last_seen_at > 5.minutes.ago %>
                  <div style="position:absolute;bottom:-2px;right: 0;">
                    <%= image_tag 'aktiivne.svg', size: "13" %>
                  </div>
                <% end %>

            </div>
          </div>


            <div class="comment-middle">
              <div class="comment-middle-up">

                <div class="comment-username">
                    <% if reply.user.admin %>
                      <%= link_to reply.user.username, (user_path(@user) if @user = reply.user), style: "color:#e0245e;" %>
                    <% else %>
                      <%= link_to reply.user.username, (user_path(@user) if @user = reply.user), style: "color:#333;" %>
                    <% end %>


                  <div class="comment-date">
                    <%= time_ago_in_words(reply.created_at).gsub('about','') + ' ago' %>
                  </div>

                </div>

              </div>

              <div class="comment-body" style="padding: <%= '10px' if reply.user == current_user %>;color: <%= 'white' if reply.user == current_user %>;background-image:<%= 'linear-gradient(139deg, rgba(250,177,219,1) 0%, rgba(255,219,126,1) 100%)' if reply.user == current_user %>">
                <%= reply.body %>
              </div>


                <div class="comment-kustuta" style="margin-top:10px;font-size: 12px;font-weight: 500;">
                  <% if user_signed_in? %>
                    <% if reply.user == current_user || @post.user == current_user || current_user.admin %>
                      <%= link_to "Delete", post_comment_path(@post, reply), method: :delete, data: {confirm: 'Kas olete kindel?'}, remote: true, style: "color:#333;" %>
                    <% end %>
                  <% end %>
                </div>

            </div>

            <div class="comment-right" style="display:inline-block;text-align: center;">
              <div class="comment-right-up">

                  <% if user_signed_in? %>

                    <div class="comment-heart heart-<%= reply.id %> <%= 'active' if reply.hearts.find { |heart| heart.user_id == current_user.id} %>" data-id="<%= reply.id %>">
                      <%= embedded_svg 'heart.svg', class: "comment-heart-img" %>
                    </div>

                  <% else %>
                      <%= link_to new_user_session_path do %>
                        <div class="comment-heart">
                          <%= embedded_svg 'heart.svg', class: "comment-heart-img" %>
                        </div>
                      <% end %>
                  <% end %>


              </div>

                    <div id="comment-<%= reply.id %>-hearts" style="margin-top:10px;font-size: 11px;">
                      <%= reply.hearts.size %>
                    </div>

            </div>


      </div>
  </div>
</div>

app/app/views/comments/_reply_form.html.erb
<div class="card ml-5">
    <div class="comment-area">
      <%= form_with model: [@post, @comment], local: false do |f| %>
        <%= f.hidden_field :parent_id %>
        <div class="form-group">
          <%= f.text_area :body, placeholder: "Reply...", class: 'form-control', id: "comment_body_reply" %>
        </div>
          <div class="send-comment icon">
            <%= f.submit "Submit", :type => :image, :src => image_path("send-comment.svg"), class: "send-comment-img", style: "outline:none;" %>
          </div>
      <% end %>
    </div>
</div>

app/app/views/comments/create.html.erb
tere

app/app/views/comments/create.js.erb
<% if @comment.parent_id == nil %>
	$('#comment_pane').prepend("<%= j render @comment %>");
	$('#comment_body').val('');
<% else %>
	$('#comment_pane_reply-<%= @comment.parent_id %>').prepend("<%= j render partial: 'comments/reply', locals: { reply: @comment } %>");
	$('#comment_body_reply').val('');
<% end %>

$('.post-comment-number').html('<%= escape_javascript(@post.comments.size) %>');

app/app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').html('');
$('.post-comment-number').html('<%= escape_javascript(@post.comments.size) %>');

app/app/views/comments/heart.js.erb
<% if @success == true %>
$(".heart-<%= @comment_id %>").addClass("active");
<% else %>
$(".heart-<%= @comment_id %>").removeClass("active");
<% end %>
$("#comment-<%= @comment_id %>-hearts").html('<%= escape_javascript(@comment_hearts) %>');

app/app/views/comments/load-more-button.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").addClass("active");
<% else %>
$(".like-<%= @post_id %>").removeClass("active");
<% end %>

$("#post-<%= @post_id %>-likes").html('<%= escape_javascript(@post_likes) %>');

app/app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")